# Generated by Django 5.2.4 on 2025-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url1',
            field=models.URLField(default='https://www.mrporter.com/variants/images/1647597340628696/in/w1500_q60.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.URLField(default='https://www.mrporter.com/variants/images/1647597340628696/in/w1500_q60.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url3',
            field=models.URLField(default='https://www.mrporter.com/variants/images/1647597340628696/in/w1500_q60.jpg'),
        ),
    ]
