# Generated by Django 5.2.4 on 2025-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='wool blazers'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='https://www.mrporter.com/variants/images/46376663162937370/ou/w2000_q60.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(default='Leather'),
        ),
    ]
