# Generated by Django 5.2.4 on 2025-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_wishitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
